# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/markw/Code/cpp/lidar-mqtt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/markw/Code/cpp/lidar-mqtt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markw/Code/cpp/lidar-mqtt/CMakeFiles /home/markw/Code/cpp/lidar-mqtt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markw/Code/cpp/lidar-mqtt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lidar-mqtt-publish

# Build rule for target.
lidar-mqtt-publish: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lidar-mqtt-publish
.PHONY : lidar-mqtt-publish

# fast build rule for target.
lidar-mqtt-publish/fast:
	$(MAKE) -f CMakeFiles/lidar-mqtt-publish.dir/build.make CMakeFiles/lidar-mqtt-publish.dir/build
.PHONY : lidar-mqtt-publish/fast

#=============================================================================
# Target rules for targets named mqtt3c

# Build rule for target.
mqtt3c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt3c
.PHONY : mqtt3c

# fast build rule for target.
mqtt3c/fast:
	$(MAKE) -f lib/CMakeFiles/mqtt3c.dir/build.make lib/CMakeFiles/mqtt3c.dir/build
.PHONY : mqtt3c/fast

#=============================================================================
# Target rules for targets named jsoncpp

# Build rule for target.
jsoncpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsoncpp
.PHONY : jsoncpp

# fast build rule for target.
jsoncpp/fast:
	$(MAKE) -f lib/CMakeFiles/jsoncpp.dir/build.make lib/CMakeFiles/jsoncpp.dir/build
.PHONY : jsoncpp/fast

#=============================================================================
# Target rules for targets named mqtt3cpp

# Build rule for target.
mqtt3cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt3cpp
.PHONY : mqtt3cpp

# fast build rule for target.
mqtt3cpp/fast:
	$(MAKE) -f lib/CMakeFiles/mqtt3cpp.dir/build.make lib/CMakeFiles/mqtt3cpp.dir/build
.PHONY : mqtt3cpp/fast

lidar-mqtt-publish.o: lidar-mqtt-publish.cpp.o

.PHONY : lidar-mqtt-publish.o

# target to build an object file
lidar-mqtt-publish.cpp.o:
	$(MAKE) -f CMakeFiles/lidar-mqtt-publish.dir/build.make CMakeFiles/lidar-mqtt-publish.dir/lidar-mqtt-publish.cpp.o
.PHONY : lidar-mqtt-publish.cpp.o

lidar-mqtt-publish.i: lidar-mqtt-publish.cpp.i

.PHONY : lidar-mqtt-publish.i

# target to preprocess a source file
lidar-mqtt-publish.cpp.i:
	$(MAKE) -f CMakeFiles/lidar-mqtt-publish.dir/build.make CMakeFiles/lidar-mqtt-publish.dir/lidar-mqtt-publish.cpp.i
.PHONY : lidar-mqtt-publish.cpp.i

lidar-mqtt-publish.s: lidar-mqtt-publish.cpp.s

.PHONY : lidar-mqtt-publish.s

# target to generate assembly for a file
lidar-mqtt-publish.cpp.s:
	$(MAKE) -f CMakeFiles/lidar-mqtt-publish.dir/build.make CMakeFiles/lidar-mqtt-publish.dir/lidar-mqtt-publish.cpp.s
.PHONY : lidar-mqtt-publish.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lidar-mqtt-publish"
	@echo "... edit_cache"
	@echo "... mqtt3c"
	@echo "... jsoncpp"
	@echo "... mqtt3cpp"
	@echo "... lidar-mqtt-publish.o"
	@echo "... lidar-mqtt-publish.i"
	@echo "... lidar-mqtt-publish.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

